### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by trohrt** [quark-os/quark-kernel#12]
We could use a bit more documentation explaining what everything does. I know it would help me get aquanted with the codebase.

**Comment by NerdyMunchkin** [comment]
I've begun documenting things in the wikis for both projects. There are some things we still need to plan, so I can't document everything. I should be able to put down enough for you to get familiar with the code though. Also, good luck on finals!

**Comment by trohrt** [comment]
@NerdyMunchkin Awesome. Anything in particular you would like me to begin working on?

**Comment by NerdyMunchkin** [comment]
A bootloader. This is a fairly complex job, but it's pretty much required to get anywhere. We can use FAT as our filesystem for now, but later on we should develop our own.  I think the issue for this already has some info on what the bootloader needs to be able to do.

**Comment by trohrt** [comment]
@NerdyMunchkin Sounds good. Will do.
