### ISSUE TITLE
HAL doesn't remap PIC interrupts

### ISSUE THREAD

**Issue by trohrt** [quark-os/quark-kernel#15]
The PIC is a device on x86/x86_64 platforms that sends interrupts for various events. In protected mode those interrupts are mapped to interrupts already used for exceptions, causing some obvious issues. The HAL needs to remap PIC interrupts when it sets up the IDT.

**Comment by NerdyMunchkin** [comment]
I copied the kernel code for doing this can used it in the HAL when it sets up interrupts on x86.
