### ISSUE TITLE
Make a native bootloader

### ISSUE THREAD

**Issue by NerdyMunchkin** [quark-os/quark-kernel#6]
Although we need to have this OS work well with GRUB for compatibility with other systems, I would like to write a bootloader seficically designed for Quark as well. Since this project is first and foremost educational, I feel it would be incomplete if we used any existing software in it.

I'm thinking the bootloader could be called Charm. It's a type of quark in the Standard Model.

**Comment by trohrt** [comment]
I agree. Being that this is a hobbiest OS, it'd be more fun to write our own. I also like the idea of naming different things off of quarks.

**Comment by NerdyMunchkin** [comment]
It seems a custom bootloader is the solution to getting an initial RAM FS. That makes it crucial to move forward with development.

**Comment by NerdyMunchkin** [comment]
We also need to specify a filesystem to structure the RAM FS into. We can call it Strange FS (yes, there is such a thing as a Strange Quark). In general, it needs to have a clever design - simple enough for the kernel to quickly locate files, but powerful enough to manage modern hard disks.

I am starting to regret not doing enough planning before writing the kernel; I've identified lots of work that needs redone for the design to be consistent. Before going into this, we should probably write the specifications for the filesystem.

**Comment by trohrt** [comment]
@NerdyMunchkin Sounds good with the first bit. On the second bit; don't worry too much. All projects take a little refactoring at some point - just be glad we didn't end up refactoring later down the project.

**Comment by NerdyMunchkin** [comment]
Charm will need to be a two-stage bootloader. The first stage is the real mode code in the MBR, and the second stage will need to be able to be loaded from Charm or GRUB. Also, there is pretty much no way to make it cross-platform. Just implement one for x86 for now, and don't worry about compatibility with GPT or EFI.

All the first stage needs to do is load the second stage. There are BIOS functions that will load sectors into memory, but they are only available in real mode so you will only have the first MB of memory available. 

The second stage will first need to ensure that it is in real mode (GRUB will load it in protected mode), and then load the kernel and ramfs. Then it will need to switch to protected mode and boot the kernel, passing parameters such as a pointer to the ramfs. Once we have a ramfs working, we can start writing usermode software to use.

**Comment by NerdyMunchkin** [comment]
Information on writing code in real mode is very sparse. I have found, however, a paragraph on the support GNU's assembler has for 16 bit code:

<http://gnu.huihoo.org/gas-2.9.1/html_node/as_203.html>

Basically, put the following directive at the top of an assembly file to make as assemble 16 bit code:

.code16

**Comment by NerdyMunchkin** [comment]
The only issue is that gcc only uses 32 bit addressing; the article has a comment on that

**Comment by trohrt** [comment]
@NerdyMunchkin I'm reading up on bootloader theory on OSDev right now. Thanks for the tip!

**Comment by NerdyMunchkin** [comment]
I started a repo for this project
