### ISSUE TITLE
Get more devs?

### ISSUE THREAD

**Issue by NerdyMunchkin** [quark-os/quark-kernel#9]
Do you think we should see if anyone else wants to join this project? We could use it to help them learn more about computer science and programming before Cyber Defense next year. On the other hand, it is a relatively complex project. I can't decide if inviting people to join is a good idea or not...

**Comment by trohrt** [comment]
@NerdyMunchkin We could go about it a bit more selectively. Someone like Jimmy or Jake I could see, but some others maybe not. With this being a FOSS project, people should be allowed to contribute freely.
